// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using contactos.Models;

namespace contactos.Migrations
{
    [DbContext(typeof(ContactosContext))]
    [Migration("20190519000723_PrimerMigra")]
    partial class PrimerMigra
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("contactos.Models.Contacto", b =>
                {
                    b.Property<long?>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("mensaje");

                    b.Property<DateTime?>("nace");

                    b.Property<string>("nombre");

                    b.HasKey("id");

                    b.ToTable("Contacto");
                });
#pragma warning restore 612, 618
        }
    }
}
